//SecretNumberAssignment4

namespace QuestionTwo.CsharpAssignment
{
  public static class SecretNumberAssignmentFour
  {

        /// <summary>
        /// SecretNumber: Checks if number entered by the user is equals to secret
        ///                 number generated by the system.
        /// <returns>Returns null, but displays message confirming success or faliure console</returns>
        /// </summary>
      public static void SecretNumber()
      {
          //Random number generation
          Random rnd = new Random();
          int num = rnd.Next(1, 10);
          Console.WriteLine ($"The Secret number is {num}");

          Console.Write("Enter the Secret number: ");

          string GuessedSecretNum = Console.ReadLine();

          bool isNumber = int.TryParse(GuessedSecretNum, out int ConvertedNum);

          if (isNumber)
          {
            if( ConvertedNum == num)
              Console.WriteLine ("You won");
            else
              Console.WriteLine ("You lost");
          }
          else
          {
            Console.WriteLine(" You have entered an invalid number");
          }
      }
  }
}